---
# true to remove install
clear_chart: false

# log level of operator
kubedb_log_level: 3

kubedb_community_licensee_name:

kubedb_community_license_key:

kubedb_community_license_email:

kubedb_community_license_cert:

# version of kubedb helm chart to install
kubedb_community_chart_version: v2021.06.23

# version of kubedb catalog helm chart to use
kubedb_catalog_chart_version: v2021.06.23

# download link for the cli. defaults to project github release link for the given kubedb version
kubedb_cli_download_link: "https://github.com/kubedb/cli/releases/download/{{ kubedb_catalog_version}}/kubedb-linux-amd64"