[all]
k8sweave-k8s-master-1 ansible_host=149.165.157.27   ip=10.0.0.24
k8sweave-k8s-master-2 ansible_host=149.165.157.115  ip=10.0.0.4
k8sweave-k8s-master-3 ansible_host=149.165.157.173  ip=10.0.0.5
k8sweave-k8s-node-1   ansible_host=149.165.172.113  ip=10.0.0.18
k8sweave-k8s-node-2   ansible_host=149.165.172.91   ip=10.0.0.23

[all:vars]
ansible_python_interpreter = /usr/bin/python3
ansible_ssh_user = ubuntu
ssh_user = ubuntu

[kube-master]
k8sweave-k8s-master-1
k8sweave-k8s-master-2
k8sweave-k8s-master-3

[kube-node]
k8sweave-k8s-master-1
k8sweave-k8s-master-2
k8sweave-k8s-master-3
k8sweave-k8s-node-1
k8sweave-k8s-node-2


[etcd]
k8sweave-k8s-master-1
k8sweave-k8s-master-2
k8sweave-k8s-master-3


[k8s-cluster:children]
kube-node
kube-master


