---
# main.yml
# Run this playbook to deploy an instance of the agave platform
#
# Assumptions:
# kubernetes cluster with valid storage class, ingress, and dns support configured
#
# Varables:
#
# Example invocation:
#
# ansible-playbook playbooks/platform/main.yml
#

- name: Deploy persistent databases via kubedb
  hosts: kube-master[0]
  become: yes
  gather_facts: no

  vars:
    agave_tenant: community
    agave_hostname: prod.agaveplatform.org

  roles:
      - role: agave-core-service-deployment
        agave_tenant: "{{ tenant }}"
        agave_hostname: "{{ hostname }}"
        tags:
          - core
          - platform

      - role: agave-auth-service-deployment
        agave_tenant: "{{ tenant }}"
        agave_hostname: "{{ hostname }}"
        tags:
          - auth
          - platform
