---
# k8s-reset.yml
# Run this playbook to wipe and reset cluster
#
# Assumptions:
# Ubuntu 20.04 LTS is assumed
#
# Varables:
#
# Example invocation:
#
# ansible-playbook -i inventory/hosts.yml playbooks/kube-reset.yml
#

- name: Spray cluster
  become: yes
  import_playbook: ../../submodules/zonca/reset.yml